export const SET_SEARCHED_MOVIES = 'SET_SEARCHED_MOVIES';
export const SET_FAVORITE_MOVIE = 'SET_FAVORITE_MOVIE';
export const SET_HIDED_MOVIE = 'SET_HIDED_MOVIE';
export const CLEAR_SEARCHED_MOVIES = 'CLEAR_SEARCHED_MOVIES';
